# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS g2o::freeglut_minimal g2o::g2o_ceres_ad g2o::stuff g2o::opengl_helper g2o::core g2o::g2o_cli_library g2o::g2o_cli_application g2o::g2o_simulator_library g2o::g2o_simulator2d_application g2o::g2o_simulator3d_application g2o::types_slam2d g2o::types_slam2d_addons g2o::types_data g2o::types_sclam2d g2o::types_slam3d g2o::types_slam3d_addons g2o::types_sba g2o::types_icp g2o::types_sim3 g2o::solver_pcg g2o::solver_dense g2o::solver_slam2d_linear g2o::solver_structure_only g2o::solver_csparse g2o::csparse_extension g2o::solver_cholmod g2o::solver_eigen g2o::g2o_hierarchical_library)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target g2o::freeglut_minimal
add_library(g2o::freeglut_minimal SHARED IMPORTED)

set_target_properties(g2o::freeglut_minimal PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/freeglut_minimal;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OpenGL::GL;OpenGL::GLU"
)

# Create imported target g2o::g2o_ceres_ad
add_library(g2o::g2o_ceres_ad INTERFACE IMPORTED)

set_target_properties(g2o::g2o_ceres_ad PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target g2o::stuff
add_library(g2o::stuff SHARED IMPORTED)

set_target_properties(g2o::stuff PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/stuff;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "rt"
)

# Create imported target g2o::opengl_helper
add_library(g2o::opengl_helper SHARED IMPORTED)

set_target_properties(g2o::opengl_helper PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/stuff;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OpenGL::GL;OpenGL::GLU"
)

# Create imported target g2o::core
add_library(g2o::core SHARED IMPORTED)

set_target_properties(g2o::core PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/core;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::stuff;g2o::g2o_ceres_ad"
)

# Create imported target g2o::g2o_cli_library
add_library(g2o::g2o_cli_library SHARED IMPORTED)

set_target_properties(g2o::g2o_cli_library PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core;dl"
)

# Create imported target g2o::g2o_cli_application
add_executable(g2o::g2o_cli_application IMPORTED)

set_target_properties(g2o::g2o_cli_application PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target g2o::g2o_simulator_library
add_library(g2o::g2o_simulator_library SHARED IMPORTED)

set_target_properties(g2o::g2o_simulator_library PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::types_slam3d_addons;g2o::types_slam3d;g2o::types_slam2d_addons;g2o::types_slam2d;g2o::core"
)

# Create imported target g2o::g2o_simulator2d_application
add_executable(g2o::g2o_simulator2d_application IMPORTED)

set_target_properties(g2o::g2o_simulator2d_application PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target g2o::g2o_simulator3d_application
add_executable(g2o::g2o_simulator3d_application IMPORTED)

set_target_properties(g2o::g2o_simulator3d_application PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target g2o::types_slam2d
add_library(g2o::types_slam2d SHARED IMPORTED)

set_target_properties(g2o::types_slam2d PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/slam2d;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core;g2o::opengl_helper"
)

# Create imported target g2o::types_slam2d_addons
add_library(g2o::types_slam2d_addons SHARED IMPORTED)

set_target_properties(g2o::types_slam2d_addons PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/slam2d_addons;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::types_slam2d;g2o::core;g2o::opengl_helper"
)

# Create imported target g2o::types_data
add_library(g2o::types_data SHARED IMPORTED)

set_target_properties(g2o::types_data PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/data;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core;g2o::types_slam2d;g2o::freeglut_minimal;g2o::opengl_helper"
)

# Create imported target g2o::types_sclam2d
add_library(g2o::types_sclam2d SHARED IMPORTED)

set_target_properties(g2o::types_sclam2d PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/sclam2d"
  INTERFACE_LINK_LIBRARIES "g2o::types_slam2d;g2o::core;g2o::opengl_helper"
)

# Create imported target g2o::types_slam3d
add_library(g2o::types_slam3d SHARED IMPORTED)

set_target_properties(g2o::types_slam3d PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/slam3d;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core;g2o::opengl_helper"
)

# Create imported target g2o::types_slam3d_addons
add_library(g2o::types_slam3d_addons SHARED IMPORTED)

set_target_properties(g2o::types_slam3d_addons PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/slam3d_addons;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::types_slam3d;g2o::core;g2o::opengl_helper"
)

# Create imported target g2o::types_sba
add_library(g2o::types_sba SHARED IMPORTED)

set_target_properties(g2o::types_sba PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/sba;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core;g2o::types_slam3d"
)

# Create imported target g2o::types_icp
add_library(g2o::types_icp SHARED IMPORTED)

set_target_properties(g2o::types_icp PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/icp;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::types_sba;g2o::types_slam3d"
)

# Create imported target g2o::types_sim3
add_library(g2o::types_sim3 SHARED IMPORTED)

set_target_properties(g2o::types_sim3 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/types/sim3;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::types_sba"
)

# Create imported target g2o::solver_pcg
add_library(g2o::solver_pcg SHARED IMPORTED)

set_target_properties(g2o::solver_pcg PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/solvers/pcg;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core"
)

# Create imported target g2o::solver_dense
add_library(g2o::solver_dense SHARED IMPORTED)

set_target_properties(g2o::solver_dense PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core"
)

# Create imported target g2o::solver_slam2d_linear
add_library(g2o::solver_slam2d_linear SHARED IMPORTED)

set_target_properties(g2o::solver_slam2d_linear PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::solver_eigen;g2o::types_slam2d"
)

# Create imported target g2o::solver_structure_only
add_library(g2o::solver_structure_only SHARED IMPORTED)

set_target_properties(g2o::solver_structure_only PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core"
)

# Create imported target g2o::solver_csparse
add_library(g2o::solver_csparse SHARED IMPORTED)

set_target_properties(g2o::solver_csparse PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/solvers/csparse;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::csparse_extension;g2o::core"
)

# Create imported target g2o::csparse_extension
add_library(g2o::csparse_extension SHARED IMPORTED)

set_target_properties(g2o::csparse_extension PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/suitesparse;${_IMPORT_PREFIX}/include/g2o/solvers/csparse;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::stuff;/usr/lib/x86_64-linux-gnu/libcxsparse.so"
)

# Create imported target g2o::solver_cholmod
add_library(g2o::solver_cholmod SHARED IMPORTED)

set_target_properties(g2o::solver_cholmod PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/solvers/cholmod"
  INTERFACE_LINK_LIBRARIES "g2o::core"
)

# Create imported target g2o::solver_eigen
add_library(g2o::solver_eigen SHARED IMPORTED)

set_target_properties(g2o::solver_eigen PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/g2o/solvers/eigen;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core"
)

# Create imported target g2o::g2o_hierarchical_library
add_library(g2o::g2o_hierarchical_library SHARED IMPORTED)

set_target_properties(g2o::g2o_hierarchical_library PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "g2o::core"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/g2oTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
